project:
  type: website

website:
  title: "Omopverse/tidyomop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Contribute to the omopverse

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

