project:
  type: website

website:
  title: "omopverse"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Contribute to the omopverse
    right:
      - text: Github
        icon: fa-github
        href: https://github.com/omopverse

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

